apiVersion: v1
kind: Service

metadata:
  name: devops-app-service

spec:
  type: NodePort

  selector:
    app: devops-app

  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30255

